language: generic

sudo: "required"

services:
  - "docker"

env:
  global:
    - DOCKER_REPO_SLUG=goeroeku/php56-fpm-alpine
    - DOCKER_REPO_TAG=5.6

script:
  - docker build --no-cache --compress --tag "$DOCKER_REPO_SLUG" .

after_script:
  - docker images

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker tag "$DOCKER_REPO_SLUG" "${DOCKER_REPO_SLUG}:latest"
  - docker tag "$DOCKER_REPO_SLUG" "${DOCKER_REPO_SLUG}:${DOCKER_REPO_TAG}"

deploy:
  provider: script
  script: docker push "${DOCKER_REPO_SLUG}:latest" && docker push "${DOCKER_REPO_SLUG}:${DOCKER_REPO_TAG}"
  on:
    branch: master
